service: snowroom

plugins:
  - serverless-s3-sync
custom:
  bucketName: snowroom.codebravo.tech
  hostedZoneName: codebravo.tech
  aliasHostedZoneId: Z3BJ6K6RIION7M   # us-west-2
  aliasDNSName: s3-website-us-west-2.amazonaws.com
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: dist

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  stage: demo
  timeout: 30

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
          Type: AWS::S3::BucketPolicy
          Properties:
            Bucket:
              Ref: StaticSite
            PolicyDocument:
              Statement:
                - Sid: PublicReadGetObject
                  Effect: Allow
                  Principal: "*"
                  Action:
                  - s3:GetObject
                  Resource:
                    Fn::Join: [
                      "", [
                        "arn:aws:s3:::",
                        {
                          "Ref": "StaticSite"
                        },
                        "/*"
                      ]
                    ]
    DnsRecord:
          Type: "AWS::Route53::RecordSet"
          Properties:
            AliasTarget:
              DNSName: ${self:custom.aliasDNSName}
              HostedZoneId: ${self:custom.aliasHostedZoneId}
            HostedZoneName: ${self:custom.hostedZoneName}.
            Name:
              Ref: StaticSite
            Type: 'A'