service: snowroom

custom:
  staticSiteBucket: snowroom.codebravo.tech
  staticSiteHostedZoneName: codebravo.tech
  aliasHostedZoneId: Z3BJ6K6RIION7M   # us-west-2
  aliasDNSName: s3-website-us-west-2.amazonaws.com

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  stage: demo
  timeout: 30

resources:
  Resources:
    StaticSiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.staticSiteBucket}
        WebsiteConfiguration:
          IndexDocument: index.html
          RoutingRules:
          - RedirectRule:
              HostName: ${self:custom.staticSiteBucket}
              HttpRedirectCode: "307"
              Protocol: http
              ReplaceKeyWith: ''
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: "404"
    StaticSiteS3BucketPolicy:
          Type: AWS::S3::BucketPolicy
          Properties:
            Bucket:
              Ref: StaticSiteBucket
            PolicyDocument:
              Statement:
                - Sid: PublicReadGetObject
                  Effect: Allow
                  Principal: "*"
                  Action:
                  - s3:GetObject
                  Resource:
                    Fn::Join: [
                      "", [
                        "arn:aws:s3:::",
                        {
                          "Ref": "StaticSiteBucket"
                        },
                        "/*"
                      ]
                    ]
    DnsRecordStaticBucket:
          Type: "AWS::Route53::RecordSet"
          Properties:
            AliasTarget:
              DNSName: ${self:custom.aliasDNSName}
              HostedZoneId: ${self:custom.aliasHostedZoneId}
            HostedZoneName: ${self:custom.staticSiteHostedZoneName}.
            Name:
              Ref: StaticSiteBucket
            Type: 'A'